version: '3.8'

services:
  redis:
    image: redis:latest
    platform: linux/arm64/v8
    ports:
      - "6379:6379"
    networks:
      - back
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure



  nest:
    image: ulysseguillot/nestqueue:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on: ['redis']
    networks:
      - back
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure



volumes:
  redis_data:

networks:
  back: