name: Build NestJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2

      - name: Change directory to back
        run: cd back

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./back

      - name: Build
        run: npm run build
        working-directory: ./back

      - name: Change directory to root
        run: cd ..

      - name: Set up Docker Compose
        run: docker compose up --build --detach --force-recreate --no-deps

      - name: Wait for the app to be ready
        run: |
          echo "Waiting for the app to be ready..."
          while ! curl -s http://localhost:3000/health; do
            sleep 5
          done

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: newman run back/back.postman_collection.json

      - name: Shut down Docker Compose
        run: docker-compose down

      - name: Create AWS PEM key file
        run: |
          echo "${{ secrets.AWS_KEY }}" > myKey.pem
          chmod 400 myKey.pem
          cp myKey.pem ./ansible/playbook/

      - name: Run deploy script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          chmod +x ./github_deploy.sh
          ./github_deploy.sh